{% set name = "napari-bigfish" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-bigfish-{{ version }}.tar.gz
  sha256: 1db253bf643137dfe99acf5e100ec9e235e6915905785d665035fa4b077d394b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - big-fish
    - magicgui
    - napari
    - numpy
    - pyperclip
    - python >=3.8
    - qtpy
    - scikit-image

test:
  imports:
    - napari_bigfish
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MontpellierRessourcesImagerie/napari-bigfish
  summary: |
    A napari-plugin providing an alternative GUI for Big-FISH.
    Big-FISH is a python package for the analysis of smFISH images.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
